---
name: CI

on:  # yamllint disable-line rule:truthy
  push:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: python -m pip install flake8 flake8-import-order doc8
      - run: flake8 .
      - run: doc8 $(git ls-files '*.rst')
      - run: yamllint --strict $(git ls-files '*.yaml')
